services:
  - type: web
    name: p2player-m3u
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /health
    autoDeploy: true

    envVars:
      - key: ORIGIN_BASE
        value: http://ativaronline.pro

      - key: ORIGIN_STREAM_BASE
        value: http://ativaronline.pro

      - key: ORIGIN_USERNAME
        value: "382664826"

      - key: ORIGIN_PASSWORD
        value: "960561913"

      - key: USERS_JSON_URL
        value: https://p2playerweb.gamer.gd/usuarios.json

      - key: USERS_CACHE_SECONDS
        value: "30"

      - key: REQUEST_TIMEOUT_MS
        value: "60000"
